# Generated by Django 4.2.30 on 2026-07-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '节点组',
                'verbose_name_plural': '节点组',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('environment', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('prod', '生产环境')], default='dev', max_length=20, verbose_name='环境')),
                ('nginx_version', models.CharField(blank=True, max_length=50, verbose_name='Nginx版本')),
                ('nginx_path', models.CharField(blank=True, help_text='自定义编译的nginx路径，例如: /usr/local/nginx/sbin/nginx', max_length=255, verbose_name='Nginx路径')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('is_locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, help_text='节点SSH凭证', null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential', verbose_name='SSH凭证')),
                ('groups', models.ManyToManyField(blank=True, related_name='nodes', to='nodes.nodegroup', verbose_name='节点组')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
    ]
