# Generated by Django 4.2.30 on 2026-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nginx_path',
            field=models.CharField(blank=True, help_text='自定义编译的nginx路径，例如: /usr/local/nginx/sbin/nginx', max_length=255, verbose_name='Nginx路径'),
        ),
    ]
