# Generated by Django 4.2.30 on 2026-08-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_probe_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次探测成功时间'),
        ),
    ]
