# Generated by Django 4.2.30 on 2026-06-23 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_credential_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0002_node_nginx_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='credential',
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.credential', verbose_name='SSH凭证')),
            ],
            options={
                'verbose_name': '节点组',
                'verbose_name_plural': '节点组',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='nodes.nodegroup', verbose_name='节点组'),
        ),
    ]
