# Generated by Django 4.2.30 on 2026-06-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_credential_name_and_more'),
        ('nodes', '0003_remove_node_credential_nodegroup_node_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='节点专属凭证，优先级高于节点组凭证', null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential', verbose_name='SSH凭证'),
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential', verbose_name='SSH凭证'),
        ),
    ]
