# Generated by Django 4.2.30 on 2026-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_normalize_nginx_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_openssh_probe_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次OpenSSH探测时间'),
        ),
        migrations.AddField(
            model_name='node',
            name='openssh_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='OpenSSH版本'),
        ),
    ]
