# Generated by Django 4.2.30 on 2026-06-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_credential_name_and_more'),
        ('nodes', '0004_node_credential_alter_nodegroup_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodegroup',
            name='credential',
        ),
        migrations.AlterField(
            model_name='node',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='节点SSH凭证', null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.credential', verbose_name='SSH凭证'),
        ),
    ]
