# Generated by Django 4.2.30 on 2026-06-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('username', models.CharField(max_length=100, verbose_name='SSH用户')),
                ('auth_type', models.CharField(choices=[('password', '密码认证'), ('key', '密钥认证')], default='password', max_length=20, verbose_name='认证方式')),
                ('password', models.TextField(blank=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, verbose_name='私钥')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'SSH凭证',
                'verbose_name_plural': 'SSH凭证',
            },
        ),
    ]
