# Generated by Django 4.2.30 on 2026-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_test_result',
            field=models.CharField(choices=[('success', '全部成功'), ('partial', '部分失败'), ('failed', '全部失败'), ('unknown', '未测试')], default='unknown', max_length=20, verbose_name='最后测试结果'),
        ),
        migrations.AddField(
            model_name='credential',
            name='last_test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后测试时间'),
        ),
    ]
