# Generated by Django 4.2.30 on 2026-08-12 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0003_nginx_available'),
        ('releases', '0003_initial_nginx_uninstall_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxUninstallTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='批次号')),
                ('resolved_prefix', models.CharField(max_length=500, verbose_name='卸载 --prefix')),
                ('backup_path', models.CharField(blank=True, max_length=500, verbose_name='拟删发布备份路径')),
                ('work_dir', models.CharField(blank=True, max_length=500, verbose_name='编译工作目录')),
                ('options_json', models.TextField(default='{}', help_text='remove_backup / remove_workdir / remove_modules / stop_if_running', verbose_name='删除选项 JSON')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('stopping', '停止服务'), ('removing_prefix', '删除安装目录'), ('removing_backup', '清理发布备份'), ('removing_extra', '清理额外目录'), ('updating_node', '更新节点状态'), ('success', '卸载成功'), ('failed', '卸载失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='当前步骤')),
                ('log_output', models.TextField(blank=True, verbose_name='完整输出日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nginx_uninstall_tasks', to='releases.taskcentertask', verbose_name='关联任务中心')),
            ],
            options={
                'verbose_name': 'Nginx 卸载任务',
                'verbose_name_plural': 'Nginx 卸载任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
