# Generated by Django 4.2.30 on 2026-09-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_uninstall', '0003_nginxuninstalltask_removing_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxuninstalltask',
            name='options_json',
            field=models.TextField(default='{}', help_text='按节点：remove_* / stop_if_running / work_dir / modules_dir / extra_paths', verbose_name='删除选项 JSON'),
        ),
    ]
