# Generated by Django 4.2.30 on 2026-08-06 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upgrade', '0002_add_third_party_module_package'),
        ('nodes', '0002_add_last_probe_at'),
        ('releases', '0002_initial_nginx_install_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxInstallTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='批次号')),
                ('remote_work_dir', models.CharField(default='/tmp/nginx-install', max_length=500, verbose_name='远程编译工作目录')),
                ('target_version', models.CharField(max_length=20, verbose_name='目标版本')),
                ('target_prefix', models.CharField(default='/usr/local/nginx', max_length=500, verbose_name='安装 --prefix')),
                ('target_configure_opts', models.TextField(blank=True, verbose_name='configure 参数')),
                ('added_modules', models.TextField(default='[]', verbose_name='新增内置模块 JSON')),
                ('added_third_party', models.TextField(default='[]', verbose_name='第三方模块 JSON')),
                ('make_jobs', models.IntegerField(default=4, verbose_name='并行编译数 (-j)')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('uploading_package', '上传源码包'), ('downloading_modules', '准备第三方模块'), ('configuring', '执行 configure'), ('compiling', '执行 make'), ('installing', 'make install'), ('starting', '启动 Nginx'), ('syncing_config', '同步配置'), ('verifying', '验证中'), ('success', '安装成功'), ('failed', '安装失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='当前步骤')),
                ('log_output', models.TextField(blank=True, verbose_name='完整输出日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sync_ok', models.BooleanField(blank=True, null=True, verbose_name='配置同步是否成功')),
                ('sync_detail', models.CharField(blank=True, max_length=255, verbose_name='配置同步摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('source_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upgrade.nginxsourcepackage', verbose_name='源码包')),
                ('task_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nginx_install_tasks', to='releases.taskcentertask', verbose_name='关联任务中心')),
            ],
            options={
                'verbose_name': 'Nginx 安装任务',
                'verbose_name_plural': 'Nginx 安装任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
