# Generated by Django 4.2.30 on 2026-06-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0004_node_credential_alter_nodegroup_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('file_path', models.CharField(max_length=500, verbose_name='配置文件路径')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('current_version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configs.config', verbose_name='关联配置')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '配置版本',
                'verbose_name_plural': '配置版本',
                'ordering': ['-version'],
                'unique_together': {('config', 'version')},
            },
        ),
    ]
