# Generated by Django 4.2.30 on 2026-07-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('file_path', models.CharField(max_length=500, verbose_name='配置文件路径')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('current_version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('sync_status', models.CharField(choices=[('pending', '等待同步'), ('syncing', '同步中'), ('success', '同步成功'), ('failed', '同步失败'), ('orphaned', '远程已删除')], default='pending', max_length=20, verbose_name='同步状态')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='最后同步错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('nodes', models.ManyToManyField(related_name='configs', to='nodes.node', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigSyncSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('main_conf_path', models.CharField(blank=True, max_length=500, verbose_name='nginx.conf 主路径')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_sync_setting', to='nodes.node', verbose_name='关联节点')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '配置同步设置',
                'verbose_name_plural': '配置同步设置',
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configs.config', verbose_name='关联配置')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '配置版本',
                'verbose_name_plural': '配置版本',
                'ordering': ['-version'],
                'unique_together': {('config', 'version')},
            },
        ),
    ]
