# Generated by Django 4.2.30 on 2026-07-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('default_remote_path', models.CharField(blank=True, help_text='如 /etc/nginx/conf.d/app.conf，创建绑定时自动填入，可修改', max_length=500, verbose_name='默认远程路径')),
                ('template_content', models.TextField(blank=True, verbose_name='内容模板')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('discovered', '远程发现导入')], default='manual', max_length=20, verbose_name='来源')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigSyncSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('main_conf_path', models.CharField(blank=True, max_length=500, verbose_name='nginx.conf 主路径')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_sync_setting', to='nodes.node', verbose_name='关联节点')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '配置同步设置',
                'verbose_name_plural': '配置同步设置',
            },
        ),
        migrations.CreateModel(
            name='ConfigNodeBinding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remote_path', models.CharField(help_text='此配置在该节点上的绝对路径', max_length=500, verbose_name='远程文件路径')),
                ('content', models.TextField(verbose_name='当前内容')),
                ('current_version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('sync_status', models.CharField(choices=[('not_synced', '未同步'), ('synced', '已同步'), ('modified', '本地已修改'), ('conflict', '冲突'), ('orphaned', '远程已删除'), ('syncing', '同步中'), ('failed', '同步失败'), ('marked_deleted', '已标记删除')], default='not_synced', max_length=20, verbose_name='同步状态')),
                ('synced_version', models.IntegerField(blank=True, help_text='最后成功推送的版本号', null=True, verbose_name='已同步版本')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='最后同步错误')),
                ('last_sync_task_id', models.BigIntegerField(blank=True, help_text='关联 TaskCenterTask.id，用于跳转任务详情', null=True, verbose_name='最后同步任务ID')),
                ('remote_content_hash', models.CharField(blank=True, help_text='最后同步时记录的远程文件 MD5，用于检测漂移', max_length=64, verbose_name='远程内容 Hash(MD5)')),
                ('drift_detected_at', models.DateTimeField(blank=True, null=True, verbose_name='漂移检测时间')),
                ('source', models.CharField(choices=[('manual', '手动绑定'), ('discovered', '远程发现')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='configs.config', verbose_name='配置标签')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_bindings', to='nodes.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '配置节点绑定',
                'verbose_name_plural': '配置节点绑定',
                'ordering': ['config__name', 'node__hostname'],
                'unique_together': {('config', 'node')},
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_versions', to='configs.config', verbose_name='关联配置')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '配置版本(旧)',
                'verbose_name_plural': '配置版本(旧)',
                'ordering': ['-version'],
                'unique_together': {('config', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BindingVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='版本内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configs.confignodebinding', verbose_name='绑定')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '绑定版本',
                'verbose_name_plural': '绑定版本',
                'ordering': ['-version'],
                'unique_together': {('binding', 'version')},
            },
        ),
    ]
