# Generated by Django 4.2.30 on 2026-07-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configversion',
            options={'ordering': ['-version'], 'verbose_name': '配置版本(旧)', 'verbose_name_plural': '配置版本(旧)'},
        ),
        migrations.RemoveField(
            model_name='config',
            name='content',
        ),
        migrations.RemoveField(
            model_name='config',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='config',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='config',
            name='last_sync_error',
        ),
        migrations.RemoveField(
            model_name='config',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='config',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='config',
            name='sync_status',
        ),
        migrations.AddField(
            model_name='config',
            name='default_remote_path',
            field=models.CharField(blank=True, help_text='如 /etc/nginx/conf.d/app.conf，创建绑定时自动填入，可修改', max_length=500, verbose_name='默认远程路径'),
        ),
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='config',
            name='source',
            field=models.CharField(choices=[('manual', '手动创建'), ('discovered', '远程发现导入')], default='manual', max_length=20, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='config',
            name='template_content',
            field=models.TextField(blank=True, help_text='创建绑定时若远程无此文件，可基于此模板生成初始内容', verbose_name='内容模板'),
        ),
        migrations.AlterField(
            model_name='configversion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_versions', to='configs.config', verbose_name='关联配置'),
        ),
        migrations.CreateModel(
            name='ConfigNodeBinding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remote_path', models.CharField(help_text='此配置在该节点上的绝对路径', max_length=500, verbose_name='远程文件路径')),
                ('content', models.TextField(verbose_name='当前内容')),
                ('current_version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('sync_status', models.CharField(choices=[('not_synced', '未同步'), ('synced', '已同步'), ('modified', '本地已修改'), ('conflict', '冲突'), ('orphaned', '远程已删除'), ('syncing', '同步中'), ('failed', '同步失败')], default='not_synced', max_length=20, verbose_name='同步状态')),
                ('synced_version', models.IntegerField(blank=True, help_text='最后成功推送的版本号', null=True, verbose_name='已同步版本')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='最后同步错误')),
                ('remote_content_hash', models.CharField(blank=True, help_text='最后同步时记录的远程文件 MD5，用于检测漂移', max_length=64, verbose_name='远程内容 Hash(MD5)')),
                ('drift_detected_at', models.DateTimeField(blank=True, null=True, verbose_name='漂移检测时间')),
                ('source', models.CharField(choices=[('manual', '手动绑定'), ('discovered', '远程发现')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='configs.config', verbose_name='配置标签')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_bindings', to='nodes.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '配置节点绑定',
                'verbose_name_plural': '配置节点绑定',
                'ordering': ['config__name', 'node__hostname'],
                'unique_together': {('config', 'node')},
            },
        ),
        migrations.CreateModel(
            name='BindingVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='版本内容')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configs.confignodebinding', verbose_name='绑定')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '绑定版本',
                'verbose_name_plural': '绑定版本',
                'ordering': ['-version'],
                'unique_together': {('binding', 'version')},
            },
        ),
    ]
