# Generated by Django 4.2.30 on 2026-06-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_remove_nodegroup_credential_alter_node_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSyncSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('main_conf_path', models.CharField(default='/etc/nginx/nginx.conf', max_length=500, verbose_name='nginx.conf 主路径')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_sync_setting', to='nodes.node', verbose_name='关联节点')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '配置同步设置',
                'verbose_name_plural': '配置同步设置',
            },
        ),
    ]
