# Generated by Django 4.2.30 on 2026-07-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigVersion',
        ),
    ]
