# Generated by Django 4.2.30 on 2026-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_delete_configversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignodebinding',
            name='sync_status',
            field=models.CharField(choices=[('not_synced', '未同步'), ('synced', '已同步'), ('modified', '本地已修改'), ('orphaned', '远程已删除'), ('failed', '同步失败'), ('marked_deleted', '已标记删除')], default='not_synced', max_length=20, verbose_name='同步状态'),
        ),
    ]
