# Generated by Django 4.2.30 on 2026-06-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_configsyncsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间'),
        ),
        migrations.AddField(
            model_name='config',
            name='sync_status',
            field=models.CharField(choices=[('pending', '等待同步'), ('syncing', '同步中'), ('success', '同步成功'), ('failed', '同步失败')], default='pending', max_length=20, verbose_name='同步状态'),
        ),
    ]
