# Generated by Django 4.2.30 on 2026-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_alter_configversion_options_remove_config_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignodebinding',
            name='sync_status',
            field=models.CharField(choices=[('not_synced', '未同步'), ('synced', '已同步'), ('modified', '本地已修改'), ('conflict', '冲突'), ('orphaned', '远程已删除'), ('syncing', '同步中'), ('failed', '同步失败'), ('marked_deleted', '已标记删除')], default='not_synced', max_length=20, verbose_name='同步状态'),
        ),
    ]
