# Generated by Django 4.2.30 on 2026-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_add_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsyncsetting',
            name='main_conf_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='nginx.conf 主路径'),
        ),
    ]
