# Generated by Django 4.2.30 on 2026-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_add_marked_deleted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='template_content',
            field=models.TextField(blank=True, verbose_name='内容模板'),
        ),
    ]
