# Generated by Django 4.2.30 on 2026-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_remove_template_content_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignodebinding',
            name='last_sync_task_id',
            field=models.BigIntegerField(blank=True, help_text='关联 TaskCenterTask.id，用于跳转任务详情', null=True, verbose_name='最后同步任务ID'),
        ),
    ]
