# Generated by Django 4.2.30 on 2026-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_alter_configsyncsetting_main_conf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='last_sync_error',
            field=models.TextField(blank=True, verbose_name='最后同步错误信息'),
        ),
        migrations.AlterField(
            model_name='config',
            name='sync_status',
            field=models.CharField(choices=[('pending', '等待同步'), ('syncing', '同步中'), ('success', '同步成功'), ('failed', '同步失败'), ('orphaned', '远程已删除')], default='pending', max_length=20, verbose_name='同步状态'),
        ),
    ]
