# Generated by Django 4.2.30 on 2026-07-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('resource', models.CharField(choices=[('nodes', '节点'), ('credentials', '凭证'), ('configs', '配置'), ('releases', '发布'), ('users', '用户'), ('roles', '角色'), ('audit', '审计')], max_length=50, verbose_name='资源')),
                ('action', models.CharField(choices=[('read', '查看'), ('create', '新增'), ('update', '编辑'), ('delete', '删除')], max_length=20, verbose_name='动作')),
            ],
            options={
                'verbose_name': '权限项',
                'verbose_name_plural': '权限项',
                'ordering': ['resource', 'action', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permissionitem', verbose_name='角色权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='头像')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('direct_permissions', models.ManyToManyField(blank=True, related_name='users', to='users.permissionitem', verbose_name='用户直授权限')),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='users.usergroup', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
