# Generated by Django 4.2.30 on 2026-06-24 14:42

from django.db import migrations, models


def seed_permission_items(apps, schema_editor):
    PermissionItem = apps.get_model('users', 'PermissionItem')
    resources = [
        ('nodes', '节点'),
        ('credentials', '凭证'),
        ('configs', '配置'),
        ('releases', '发布'),
        ('users', '用户'),
        ('roles', '角色'),
        ('audit', '审计'),
    ]
    actions = [
        ('read', '查看'),
        ('create', '新增'),
        ('update', '编辑'),
        ('delete', '删除'),
    ]

    for resource_code, resource_name in resources:
        for action_code, action_name in actions:
            code = f'{resource_code}.{action_code}'
            name = f'{resource_name}-{action_name}'
            PermissionItem.objects.update_or_create(
                code=code,
                defaults={
                    'name': name,
                    'resource': resource_code,
                    'action': action_code,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup_userprofile_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('resource', models.CharField(choices=[('nodes', '节点'), ('credentials', '凭证'), ('configs', '配置'), ('releases', '发布'), ('users', '用户'), ('roles', '角色'), ('audit', '审计')], max_length=50, verbose_name='资源')),
                ('action', models.CharField(choices=[('read', '查看'), ('create', '新增'), ('update', '编辑'), ('delete', '删除')], max_length=20, verbose_name='动作')),
            ],
            options={
                'verbose_name': '权限项',
                'verbose_name_plural': '权限项',
                'ordering': ['resource', 'action', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.usergroup', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permissionitem', verbose_name='角色权限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direct_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.permissionitem', verbose_name='用户直授权限'),
        ),
        migrations.RunPython(seed_permission_items, migrations.RunPython.noop),
    ]
