# Generated by Django 4.2.30 on 2026-07-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userteam'),
    ]

    operations = [
    ]
