# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_seed_nginx_ops_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="连续登录失败次数",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_locked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="登录临时锁定截止时间",
            ),
        ),
    ]
