# Generated by Django 4.2.30 on 2026-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_teams_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='teams', to='users.usergroup', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='permissionitem',
            name='resource',
            field=models.CharField(choices=[('nodes', '节点'), ('credentials', '凭证'), ('configs', '配置'), ('releases', '发布'), ('users', '用户'), ('roles', '角色'), ('teams', '用户组'), ('audit', '审计')], max_length=50, verbose_name='资源'),
        ),
    ]
