# Generated by Django 4.2.30

from django.db import migrations
from apps.users.perm_defs import all_permission_items


def create_all_permissions(apps, schema_editor):
    PermissionItem = apps.get_model("users", "PermissionItem")
    for item in all_permission_items():
        PermissionItem.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "resource": item["resource"],
                "action": item["action"],
            },
        )


def remove_all_permissions(apps, schema_editor):
    PermissionItem = apps.get_model("users", "PermissionItem")
    PermissionItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userteam_roles_alter_permissionitem_resource'),
    ]

    operations = [
        migrations.RunPython(
            create_all_permissions,
            reverse_code=remove_all_permissions,
        ),
    ]