# Generated by Django 4.2.30 on 2026-08-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_openssh_upgrade_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionitem',
            name='resource',
            field=models.CharField(choices=[('nodes', '节点管理'), ('credentials', '凭证管理'), ('configs', '配置管理'), ('releases', '发布管理'), ('upgrade', 'Nginx 升级'), ('nginx_install', 'Nginx 安装'), ('nginx_service', 'Nginx 启停'), ('nginx_uninstall', 'Nginx 卸载'), ('openssh_upgrade', 'OpenSSH 升级'), ('users', '用户管理'), ('roles', '角色管理'), ('teams', '用户组管理'), ('audit', '审计日志'), ('settings', '系统设置')], max_length=50, verbose_name='资源'),
        ),
    ]
