# Generated by Django 4.2.30 on 2026-07-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_all_permissions'),
    ]

    operations = [
    ]
