# Generated by Django 4.2.30 on 2026-09-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fine_grained_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionitem',
            name='action',
            field=models.CharField(choices=[('read', '查看'), ('create', '新增'), ('update', '编辑'), ('delete', '删除'), ('ssh_test', 'SSH测试'), ('lock', '锁定'), ('unlock', '解锁'), ('enable', '启用'), ('sync', '配置同步'), ('publish', '发布/回滚'), ('operate', '启停操作'), ('execute', '执行操作')], max_length=20, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='permissionitem',
            name='resource',
            field=models.CharField(choices=[('nodes', '节点管理'), ('credentials', '凭证管理'), ('configs', '配置管理'), ('releases', '发布管理'), ('upgrade', 'Nginx 升级'), ('nginx_install', 'Nginx 安装'), ('nginx_service', 'Nginx 启停'), ('nginx_uninstall', 'Nginx 卸载'), ('users', '用户管理'), ('roles', '角色管理'), ('teams', '用户组管理'), ('audit', '审计日志'), ('settings', '系统设置')], max_length=50, verbose_name='资源'),
        ),
    ]
