# Generated by Django 4.2.30 on 2026-09-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_permissionitem_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_session_key',
            field=models.CharField(blank=True, default='', help_text='用于检测多点登录冲突', max_length=40, verbose_name='当前会话密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_agent',
            field=models.TextField(blank=True, default='', verbose_name='最近登录浏览器'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='最近登录IP'),
        ),
        migrations.AlterField(
            model_name='permissionitem',
            name='resource',
            field=models.CharField(choices=[('nodes', '节点管理'), ('credentials', '凭证管理'), ('configs', '配置管理'), ('releases', '发布管理'), ('upgrade', 'Nginx 安装/升级'), ('nginx_service', 'Nginx 启停'), ('nginx_uninstall', 'Nginx 卸载'), ('audit', '审计日志'), ('settings', '系统设置')], max_length=50, verbose_name='资源'),
        ),
    ]
