# Generated by Django 4.2.30 on 2026-09-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='前端心跳轮询自动更新，超过 30 秒视为离线', null=True, verbose_name='最近活跃时间'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(error_messages={'unique': '角色名称已存在'}, max_length=100, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='name',
            field=models.CharField(error_messages={'unique': '用户组已存在'}, max_length=100, unique=True, verbose_name='组名'),
        ),
    ]
