# Generated by Django 4.2.30 on 2026-07-13 13:45

import apps.upgrade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('releases', '0002_releasetask_binding_releasetask_publish_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxSourcePackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='包名称')),
                ('version', models.CharField(max_length=20, verbose_name='Nginx 版本号')),
                ('package_file', models.FileField(help_text='支持 .tar.gz / .tgz 格式', upload_to=apps.upgrade.models.nginx_package_upload_path, verbose_name='源码包文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('file_md5', models.CharField(blank=True, max_length=64, verbose_name='文件 MD5')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_official', models.BooleanField(default=False, verbose_name='是否官方包')),
                ('custom_modules_included', models.TextField(blank=True, help_text='JSON 列表，如 [{"name":"headers-more","version":"v0.37"}]', verbose_name='预置第三方模块')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'Nginx 源码包',
                'verbose_name_plural': 'Nginx 源码包',
                'ordering': ['-created_at'],
                'unique_together': {('version', 'uploaded_by')},
            },
        ),
        migrations.CreateModel(
            name='NginxUpgradeTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_mode', models.CharField(choices=[('install', '全新安装（无旧版本）'), ('upgrade', '平滑升级（同路径）'), ('switch_path', '切换路径升级（不同 --prefix）')], default='upgrade', max_length=20, verbose_name='升级模式')),
                ('remote_work_dir', models.CharField(default='/tmp/nginx-upgrade', help_text='源码包将上传到此目录，编译也在此进行', max_length=500, verbose_name='节点上的编译工作目录')),
                ('current_version', models.CharField(blank=True, max_length=50, verbose_name='当前版本')),
                ('current_configure_opts', models.TextField(blank=True, help_text='从目标节点自动获取的原始编译参数', verbose_name='当前编译参数（nginx -V）')),
                ('current_configure_path', models.CharField(blank=True, max_length=500, verbose_name='当前 --prefix 路径')),
                ('current_binary_path', models.CharField(blank=True, max_length=500, verbose_name='当前 nginx 二进制路径')),
                ('target_version', models.CharField(max_length=20, verbose_name='目标版本')),
                ('target_configure_opts', models.TextField(blank=True, help_text='基于 current_configure_opts 调整后的最终参数', verbose_name='调整后的编译参数')),
                ('target_prefix', models.CharField(blank=True, max_length=500, verbose_name='目标 --prefix')),
                ('added_modules', models.TextField(default='[]', help_text='JSON列表，如 ["--with-http_v3_module"]', verbose_name='新增的编译参数')),
                ('removed_modules', models.TextField(default='[]', help_text='JSON列表，如 ["--with-mail"]', verbose_name='移除的编译参数')),
                ('added_third_party', models.TextField(default='[]', help_text='JSON列表，如 [{"name":"echo-nginx","git_url":"...","branch":"v0.63"}]', verbose_name='新增第三方模块')),
                ('make_jobs', models.IntegerField(default=4, verbose_name='并行编译数 (-j)')),
                ('old_binary_backup', models.CharField(blank=True, max_length=500, verbose_name='旧二进制备份路径')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('fetching_config', '获取当前编译参数'), ('uploading_package', '上传源码包到节点'), ('downloading_modules', '下载第三方模块'), ('configuring', '执行 configure'), ('compiling', '执行 make'), ('backing_up', '备份旧版本'), ('replacing_binary', '替换二进制文件'), ('upgrading', '平滑升级中'), ('verifying', '验证中'), ('success', '升级成功'), ('failed', '升级失败'), ('rollback', '已回滚'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='当前步骤')),
                ('log_output', models.TextField(blank=True, verbose_name='完整输出日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_tasks', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('source_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upgrade.nginxsourcepackage', verbose_name='源码包')),
                ('task_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.taskcentertask', verbose_name='任务中心关联')),
            ],
            options={
                'verbose_name': 'Nginx 升级任务',
                'verbose_name_plural': 'Nginx 升级任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
