# Generated by Django 4.2.30 on 2026-07-31 07:08

import apps.upgrade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxupgradetask',
            name='added_third_party',
            field=models.TextField(default='[]', help_text='JSON列表，在线: {"name","source":"git","git_url","branch"}；离线: {"name","source":"package","package_id"}', verbose_name='新增第三方模块'),
        ),
        migrations.CreateModel(
            name='NginxThirdPartyModulePackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='对应远程目录名与 --add-module 下目录名，如 nginx-module-sts', max_length=100, verbose_name='模块名称')),
                ('version', models.CharField(blank=True, help_text='展示用，如 v1.2.1', max_length=50, verbose_name='版本/标签')),
                ('package_file', models.FileField(help_text='支持 .tar.gz / .tgz / .zip 格式', upload_to=apps.upgrade.models.nginx_module_package_upload_path, verbose_name='模块包文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('file_md5', models.CharField(blank=True, max_length=64, verbose_name='文件 MD5')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '第三方模块包',
                'verbose_name_plural': '第三方模块包',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version', 'uploaded_by')},
            },
        ),
    ]
