# Generated by Django 4.2.30 on 2026-07-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔'), ('json', 'JSON')], default='string', max_length=20, verbose_name='值类型')),
                ('group', models.CharField(max_length=50, verbose_name='配置分组')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='占位提示')),
                ('options', models.TextField(blank=True, verbose_name='可选值JSON')),
                ('is_required', models.BooleanField(default=True, verbose_name='必填')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['group', 'sort_order'],
            },
        ),
    ]
