# Generated by Django 4.2.30 on 2026-07-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCenterTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('release_publish', '发布配置'), ('release_rollback', '回滚配置'), ('credential_enable_test', '凭证启用测试'), ('node_batch_test', '节点批量测试'), ('config_batch_sync', '配置批量同步'), ('other', '其他任务')], default='other', max_length=40, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('detail', models.TextField(blank=True, verbose_name='任务说明')),
                ('result', models.TextField(blank=True, verbose_name='任务结果')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('source_batch', models.CharField(blank=True, max_length=64, verbose_name='来源批次')),
                ('target_hostnames', models.TextField(blank=True, verbose_name='目标主机名')),
                ('target_ips', models.TextField(blank=True, verbose_name='目标IP')),
                ('target_configs', models.TextField(blank=True, verbose_name='目标配置')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trigger_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
            ],
            options={
                'verbose_name': '任务中心',
                'verbose_name_plural': '任务中心',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='批次号')),
                ('status', models.CharField(choices=[('pending', '等待发布'), ('running', '发布中'), ('success', '发布成功'), ('failed', '发布失败'), ('rollback', '已回滚'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config', verbose_name='目标配置')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.configversion', verbose_name='发布版本')),
            ],
            options={
                'verbose_name': '发布任务',
                'verbose_name_plural': '发布任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('action', models.CharField(choices=[('publish', '发布'), ('rollback', '回滚')], max_length=20, verbose_name='操作类型')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config', verbose_name='目标配置')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('release_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='releases.releasetask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '发布历史',
                'verbose_name_plural': '发布历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
