# Generated by Django 4.2.30 on 2026-06-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0004_node_credential_alter_nodegroup_credential'),
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待发布'), ('running', '发布中'), ('success', '发布成功'), ('failed', '发布失败'), ('rollback', '已回滚')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config', verbose_name='目标配置')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.configversion', verbose_name='发布版本')),
            ],
            options={
                'verbose_name': '发布任务',
                'verbose_name_plural': '发布任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('action', models.CharField(choices=[('publish', '发布'), ('rollback', '回滚')], max_length=20, verbose_name='操作类型')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config', verbose_name='目标配置')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('release_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='releases.releasetask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '发布历史',
                'verbose_name_plural': '发布历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
