# Generated by Django 4.2.30 on 2026-07-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_alter_configversion_options_remove_config_content_and_more'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='binding',
            field=models.ForeignKey(blank=True, help_text='发布将沿用绑定的 remote_path 和 content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_tasks', to='configs.confignodebinding', verbose_name='关联绑定'),
        ),
        migrations.AddField(
            model_name='releasetask',
            name='publish_version',
            field=models.IntegerField(blank=True, help_text='绑定的版本号，如 V3 表示绑定第 3 版', null=True, verbose_name='发布版本号'),
        ),
        migrations.AddField(
            model_name='releasetask',
            name='remote_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='远程路径'),
        ),
        migrations.AlterField(
            model_name='releasehistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='batch_number',
            field=models.CharField(db_index=True, max_length=32, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config', verbose_name='配置标签'),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.bindingversion', verbose_name='发布版本'),
        ),
        migrations.AlterField(
            model_name='taskcentertask',
            name='operation_type',
            field=models.CharField(choices=[('release_publish', '发布配置'), ('release_rollback', '回滚配置'), ('credential_enable_test', '凭证启用测试'), ('node_batch_test', '节点批量测试'), ('node_system_info', '节点系统信息采集'), ('node_nginx_version', 'Nginx 版本检测'), ('config_batch_sync', '配置批量同步'), ('config_discover', '配置发现扫描'), ('config_drift_check', '配置漂移检测'), ('nginx_upgrade', 'Nginx 编译升级'), ('nginx_rollback', 'Nginx 升级回滚'), ('other', '其他任务')], default='other', max_length=40, verbose_name='任务类型'),
        ),
    ]
