# Generated by Django 4.2.30 on 2026-06-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='status',
            field=models.CharField(choices=[('pending', '等待发布'), ('running', '发布中'), ('success', '发布成功'), ('failed', '发布失败'), ('rollback', '已回滚'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
