# Generated by Django 4.2.30 on 2026-08-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcentertask',
            name='operation_type',
            field=models.CharField(choices=[('release_publish', '发布配置'), ('release_rollback', '回滚配置'), ('credential_enable_test', '凭证启用测试'), ('node_ssh_test', '节点SSH测试'), ('node_batch_test', '节点批量测试'), ('node_system_info', '节点系统信息采集'), ('node_nginx_version', 'Nginx 版本检测'), ('config_batch_sync', '配置批量同步'), ('config_discover', '配置发现扫描'), ('config_drift_check', '配置漂移检测'), ('config_glob_preview', '配置Glob预览'), ('nginx_upgrade', 'Nginx 编译升级'), ('nginx_rollback', 'Nginx 升级回滚'), ('nginx_service_control', 'Nginx 服务启停'), ('nginx_install', 'Nginx 全新安装'), ('other', '其他任务')], default='other', max_length=40, verbose_name='任务类型'),
        ),
    ]
