# Generated by Django 4.2.30 on 2026-07-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_taskcentertask_target_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcentertask',
            name='operation_type',
            field=models.CharField(choices=[('release_publish', '发布配置'), ('release_rollback', '回滚配置'), ('credential_enable_test', '凭证启用测试'), ('node_batch_test', '节点批量测试'), ('config_batch_sync', '配置批量同步'), ('other', '其他任务')], default='other', max_length=40, verbose_name='任务类型'),
        ),
    ]
