# Generated by Django 4.2.30 on 2026-07-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='浏览器信息')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='结果')),
                ('fail_reason', models.CharField(blank=True, choices=[('', '未知'), ('user_not_found', '用户不存在'), ('wrong_password', '密码错误'), ('user_locked', '用户已锁定'), ('user_inactive', '用户未激活')], help_text='区分：用户不存在/密码错误/用户已锁定/用户未激活', max_length=50, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('action', models.CharField(max_length=255, verbose_name='动作')),
                ('ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='结果')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('task_center_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='任务中心ID')),
                ('source_batch', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='来源批次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
