# Generated by Django 4.2.30 on 2026-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('', '未知'), ('user_not_found', '用户不存在'), ('wrong_password', '密码错误'), ('user_locked', '用户已锁定'), ('user_inactive', '用户未激活')], help_text='区分：用户不存在/密码错误/用户已锁定/用户未激活', max_length=50, verbose_name='失败原因'),
        ),
    ]
