# Generated by Django 4.2.30 on 2026-08-17 09:18

import apps.openssh_upgrade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0005_node_last_openssh_probe_at_node_openssh_version'),
        ('releases', '0003_initial_nginx_uninstall_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSSHSourcePackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='包名称')),
                ('version', models.CharField(max_length=50, verbose_name='OpenSSH 版本号')),
                ('package_file', models.FileField(help_text='支持 .tar.gz / .tgz 格式', upload_to=apps.openssh_upgrade.models.openssh_package_upload_path, verbose_name='源码包文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('file_md5', models.CharField(blank=True, max_length=64, verbose_name='文件 MD5')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'OpenSSH 源码包',
                'verbose_name_plural': 'OpenSSH 源码包',
                'ordering': ['-created_at'],
                'unique_together': {('version', 'uploaded_by')},
            },
        ),
        migrations.CreateModel(
            name='OpenSSHUpgradeTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upgrade', 'OpenSSH 升级'), ('rollback', 'OpenSSH 回滚')], default='upgrade', max_length=20, verbose_name='操作')),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='升级 OSI-YYMMDD-NNNN；回滚 OSR-YYMMDD-NNNN', max_length=32, verbose_name='批次号')),
                ('current_version', models.CharField(blank=True, max_length=50, verbose_name='当前版本')),
                ('target_version', models.CharField(blank=True, max_length=50, verbose_name='目标版本')),
                ('configure_opts', models.TextField(blank=True, verbose_name='configure 参数')),
                ('target_prefix', models.CharField(blank=True, max_length=500, verbose_name='目标安装前缀 (--prefix)')),
                ('make_jobs', models.IntegerField(default=4, verbose_name='并行编译数 (-j)')),
                ('remote_work_dir', models.CharField(default='/tmp/openssh-upgrade', max_length=500, verbose_name='节点编译工作目录')),
                ('test_port', models.IntegerField(default=2222, verbose_name='预验证备用端口')),
                ('reconnect_grace_seconds', models.IntegerField(default=60, verbose_name='看门狗回滚宽限（秒）')),
                ('auto_rollback', models.BooleanField(default=True, verbose_name='失败自动回滚')),
                ('binaries', models.JSONField(blank=True, default=dict, verbose_name='二进制路径映射')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否 root')),
                ('use_sudo', models.BooleanField(default=False, verbose_name='使用免密 sudo')),
                ('manage_mode', models.CharField(default='binary', help_text='systemctl | binary', max_length=20, verbose_name='托管方式')),
                ('manage_unit', models.CharField(blank=True, max_length=50, verbose_name='托管 unit')),
                ('sshd_config_path', models.CharField(default='/etc/ssh/sshd_config', max_length=500, verbose_name='sshd 配置路径')),
                ('sshd_port', models.IntegerField(default=22, verbose_name='sshd 监听端口')),
                ('sshd_binary', models.CharField(blank=True, max_length=500, verbose_name='sshd 二进制路径')),
                ('home_dir', models.CharField(blank=True, max_length=255, verbose_name='远程主目录')),
                ('backup_dir', models.CharField(blank=True, max_length=500, verbose_name='备份根目录')),
                ('backup_manifest_json', models.TextField(default='{}', verbose_name='备份清单 JSON')),
                ('rollback_script_path', models.CharField(blank=True, max_length=500, verbose_name='远端回滚脚本路径')),
                ('ok_marker', models.CharField(blank=True, max_length=500, verbose_name='成功标记路径')),
                ('rolled_back_marker', models.CharField(blank=True, max_length=500, verbose_name='回滚标记路径')),
                ('upgraded_openssh_version', models.CharField(blank=True, max_length=50, verbose_name='升级后版本（已实证）')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('probing', '预检探测'), ('building', '上传编译'), ('verifying', '预验证新二进制'), ('backing_up', '备份旧版本'), ('switching', '切换并重启 sshd'), ('confirming', '连接实证'), ('success', '升级/回滚成功'), ('failed', '失败'), ('rolled_back', '已自动回滚'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='当前步骤')),
                ('log_output', models.TextField(blank=True, verbose_name='完整输出日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node', verbose_name='目标节点')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('source_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openssh_upgrade.opensshsourcepackage', verbose_name='源码包')),
                ('task_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openssh_upgrade_tasks', to='releases.taskcentertask', verbose_name='关联任务中心')),
            ],
            options={
                'verbose_name': 'OpenSSH 升级任务',
                'verbose_name_plural': 'OpenSSH 升级任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
